# These are supported funding model platforms

# github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPEN_COLLECTIVE
# ko_fi: YOUR_KO_FI_USERNAME
# tidelift: npm/YOUR_PACKAGE_NAME
# community_bridge: YOUR_PROJECT_NAME
# liberapay: YOUR_LIBERAPAY_USERNAME
# issuehunt: YOUR_ISSUEHUNT_USERNAME
# otechie: YOUR_OTECHIE_USERNAME
# lfx_crowdfunding: YOUR_PROJECT_NAME
# custom: ['https://your-website.com', 'https://another-website.com']

# Uncomment and configure the funding platforms you want to use
